"""add structured column to source_documents

Revision ID: 3c523ff213af
Revises: b6778e0f22c0
Create Date: 2026-09-15 00:46:17.235991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c523ff213af'
down_revision: Union[str, None] = 'b6778e0f22c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_documents', sa.Column('structured', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_documents', 'structured')
    # ### end Alembic commands ###
